### ISSUE TITLE
code is not working properly

### ISSUE THREAD

**Issue by i6ii** [letssolvetogether/OMRChecker#2]
i use your code ,but it not provide true solution .it produce '0' score every time why???

**Comment by shreyas29** [comment]
Yes. It's a bug introduced in new version of app. I will find it out and fix it.

**Comment by shreyas29** [comment]
I am woking on making app size smaller so i am bit busy in that. After that I will look into this defect.

**Comment by shreyas29** [comment]
This bug is introduced after v1.1.9

**Comment by shreyas29** [comment]
@i6ii I have fixed this issue. Please verify from your side as well.
